// openrouter.ts - League of Experts API Service
// Generated by Codex, reviewed and enhanced by Tiger

// ============================================
// Types
// ============================================

export type ExpertModel =
  | 'openai/gpt-4o'
  | 'anthropic/claude-3-5-sonnet'
  | 'google/gemini-pro'
  | 'deepseek/deepseek-chat';

export interface ExpertResponse {
  modelName: ExpertModel;
  modelDisplay: string;
  responseText: string;
  latency: number;
  status: 'success' | 'error';
  error?: string;
}

export interface ExpertConfig {
  model: ExpertModel;
  displayName: string;
  systemPrompt: string;
  epistemicBoundary: string;
}

// ============================================
// Expert Configurations (League of Experts Style)
// ============================================

const EXPERT_CONFIGS: ExpertConfig[] = [
  {
    model: 'openai/gpt-4o',
    displayName: 'GPT-4',
    systemPrompt: `You are a Strategic Analysis Expert in the League of Experts.
Your role: Provide broad strategic analysis with market insights.
Your strength: Pattern recognition, trend analysis, creative solutions.

EPISTEMIC BOUNDARIES:
- You CAN provide strategic frameworks and market analysis
- You CANNOT provide specific legal or medical advice
- Say "outside my expertise" if asked about specialized domains
- Express uncertainty when data is limited`,
    epistemicBoundary: 'Strategic analysis, market trends, creative solutions',
  },
  {
    model: 'anthropic/claude-3-5-sonnet',
    displayName: 'Claude',
    systemPrompt: `You are a Risk & Compliance Expert in the League of Experts.
Your role: Identify risks, regulatory concerns, and ethical considerations.
Your strength: Careful analysis, nuanced reasoning, risk identification.

EPISTEMIC BOUNDARIES:
- You CAN identify potential risks and regulatory concerns
- You CANNOT provide definitive legal rulings
- Say "requires specialist review" for complex legal matters
- Highlight uncertainty and recommend expert consultation when needed`,
    epistemicBoundary: 'Risk analysis, compliance concerns, ethical review',
  },
  {
    model: 'google/gemini-pro',
    displayName: 'Gemini',
    systemPrompt: `You are a Competitive Intelligence Expert in the League of Experts.
Your role: Analyze competitive landscape and market positioning.
Your strength: Data synthesis, competitive analysis, market dynamics.

EPISTEMIC BOUNDARIES:
- You CAN analyze competitive positioning and market dynamics
- You CANNOT predict specific competitor actions with certainty
- Say "insufficient data" when market information is limited
- Acknowledge when analysis is based on assumptions`,
    epistemicBoundary: 'Competitive analysis, market positioning, data synthesis',
  },
  {
    model: 'deepseek/deepseek-chat',
    displayName: 'DeepSeek',
    systemPrompt: `You are a Financial Analysis Expert in the League of Experts.
Your role: Provide financial modeling insights and quantitative analysis.
Your strength: Numbers, financial projections, ROI calculations.

EPISTEMIC BOUNDARIES:
- You CAN provide financial frameworks and modeling approaches
- You CANNOT guarantee financial outcomes
- Say "model assumptions" when projections depend on uncertain inputs
- Highlight sensitivity to key variables`,
    epistemicBoundary: 'Financial analysis, quantitative modeling, ROI assessment',
  },
];

// ============================================
// API Configuration
// ============================================

const OPENROUTER_API = 'https://openrouter.ai/api/v1/chat/completions';

function getApiKey(): string {
  // In Electron, this would come from secure storage
  // For now, check environment variable
  return process.env.OPENROUTER_API_KEY || '';
}

// ============================================
// Query Single Expert
// ============================================

async function queryExpert(
  config: ExpertConfig,
  userQuery: string
): Promise<ExpertResponse> {
  const startTime = performance.now();

  try {
    const response = await fetch(OPENROUTER_API, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${getApiKey()}`,
        'HTTP-Referer': 'https://league-of-experts.solunai.co.jp',
        'X-Title': 'League of Experts',
      },
      body: JSON.stringify({
        model: config.model,
        messages: [
          { role: 'system', content: config.systemPrompt },
          { role: 'user', content: userQuery },
        ],
        temperature: 0.7,
        max_tokens: 1000,
      }),
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    const data = await response.json();
    const latency = Math.round(performance.now() - startTime);

    return {
      modelName: config.model,
      modelDisplay: config.displayName,
      responseText: data.choices[0]?.message?.content || 'No response generated',
      latency,
      status: 'success',
    };
  } catch (error) {
    const latency = Math.round(performance.now() - startTime);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';

    console.error(`[LoE] Error querying ${config.displayName}:`, errorMessage);

    return {
      modelName: config.model,
      modelDisplay: config.displayName,
      responseText: '',
      latency,
      status: 'error',
      error: errorMessage,
    };
  }
}

// ============================================
// Query All Experts (Parallel)
// ============================================

export async function queryAllExperts(query: string): Promise<ExpertResponse[]> {
  console.log(`[LoE] Querying ${EXPERT_CONFIGS.length} experts...`);

  const promises = EXPERT_CONFIGS.map(config => queryExpert(config, query));
  const results = await Promise.allSettled(promises);

  return results.map((result, index) => {
    if (result.status === 'fulfilled') {
      return result.value;
    }

    // Handle rejected promises (shouldn't happen with our error handling, but just in case)
    return {
      modelName: EXPERT_CONFIGS[index].model,
      modelDisplay: EXPERT_CONFIGS[index].displayName,
      responseText: '',
      latency: 0,
      status: 'error' as const,
      error: 'Promise rejected',
    };
  });
}

// ============================================
// Katana Mode (Devil's Advocate)
// ============================================

export interface KatanaCritique {
  type: 'warning' | 'error' | 'info';
  message: string;
  source?: string;
}

export async function runKatanaMode(
  query: string,
  expertResponses: ExpertResponse[]
): Promise<KatanaCritique[]> {
  const katanaPrompt = `You are the Devil's Advocate (Katana Mode) in the League of Experts.

Your ONLY job is to challenge, critique, and find weaknesses. You are not here to agree.

ORIGINAL QUERY: ${query}

EXPERT RESPONSES:
${expertResponses.map(r => `[${r.modelDisplay}]: ${r.responseText}`).join('\n\n')}

Analyze these responses and provide critiques. Look for:
1. Logical weaknesses or gaps
2. Overconfident claims without evidence
3. Potential hallucinations or unfounded assumptions
4. Missing considerations
5. Contradictions between experts
6. Risks not adequately addressed

Return your critiques as a JSON array:
[
  { "type": "warning|error|info", "message": "Your critique" },
  ...
]

Be ruthless but fair. Maximum 5 critiques.`;

  try {
    const response = await fetch(OPENROUTER_API, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${getApiKey()}`,
      },
      body: JSON.stringify({
        model: 'anthropic/claude-3-5-sonnet', // Claude is good at critique
        messages: [{ role: 'user', content: katanaPrompt }],
        temperature: 0.3, // Lower temperature for more focused critique
        max_tokens: 500,
      }),
    });

    const data = await response.json();
    const content = data.choices[0]?.message?.content || '[]';

    // Parse JSON from response
    const jsonMatch = content.match(/\[[\s\S]*\]/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }

    return [];
  } catch (error) {
    console.error('[LoE] Katana Mode error:', error);
    return [{ type: 'error', message: 'Katana Mode analysis failed' }];
  }
}

// ============================================
// Synthesis (Chairman)
// ============================================

export interface SynthesisResult {
  decision: string;
  confidenceScore: number;
  keyPoints: string[];
  actions: string[];
  memoryNote?: string;
}

export async function synthesizeResponses(
  query: string,
  expertResponses: ExpertResponse[],
  critiques: KatanaCritique[]
): Promise<SynthesisResult> {
  const synthesisPrompt = `You are the Chairman/Arbiter in the League of Experts.

CRITICAL RULES:
1. Do NOT add new facts - only synthesize what experts provided
2. Weigh expert outputs based on their epistemic boundaries
3. Resolve contradictions by noting them explicitly
4. Incorporate Devil's Advocate critiques
5. Produce traceable reasoning

ORIGINAL QUERY: ${query}

EXPERT RESPONSES:
${expertResponses.filter(r => r.status === 'success').map(r => `[${r.modelDisplay}]: ${r.responseText}`).join('\n\n')}

DEVIL'S ADVOCATE CRITIQUES:
${critiques.map(c => `[${c.type.toUpperCase()}]: ${c.message}`).join('\n')}

Synthesize into a final decision. Return as JSON:
{
  "decision": "1-2 sentence final recommendation",
  "confidenceScore": 0-100,
  "keyPoints": ["point 1", "point 2", ...],
  "actions": ["action 1", "action 2", ...],
  "memoryNote": "optional note for future reference"
}`;

  try {
    const response = await fetch(OPENROUTER_API, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${getApiKey()}`,
      },
      body: JSON.stringify({
        model: 'anthropic/claude-3-opus', // Chairman uses the most capable model
        messages: [{ role: 'user', content: synthesisPrompt }],
        temperature: 0.5,
        max_tokens: 800,
      }),
    });

    const data = await response.json();
    const content = data.choices[0]?.message?.content || '{}';

    // Parse JSON from response
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }

    return {
      decision: 'Unable to synthesize - please review expert responses manually',
      confidenceScore: 0,
      keyPoints: [],
      actions: [],
    };
  } catch (error) {
    console.error('[LoE] Synthesis error:', error);
    return {
      decision: 'Synthesis failed - please review expert responses manually',
      confidenceScore: 0,
      keyPoints: [],
      actions: [],
    };
  }
}

// ============================================
// Full Pipeline
// ============================================

export async function runLeagueOfExperts(query: string): Promise<{
  expertResponses: ExpertResponse[];
  critiques: KatanaCritique[];
  synthesis: SynthesisResult;
}> {
  // Stage 1: Query all experts in parallel
  const expertResponses = await queryAllExperts(query);

  // Stage 2: Run Devil's Advocate (Katana Mode)
  const critiques = await runKatanaMode(query, expertResponses);

  // Stage 3: Synthesize with Chairman
  const synthesis = await synthesizeResponses(query, expertResponses, critiques);

  return {
    expertResponses,
    critiques,
    synthesis,
  };
}

export { EXPERT_CONFIGS };
