// App.tsx - League of Experts Main Component
// Generated by Codex, reviewed and enhanced by Tiger

import React, { useState } from 'react';

// ============================================
// TypeScript Interfaces
// ============================================

interface ExpertResponse {
  model: string;
  modelDisplay: string;
  response: string;
  confidence: number;
  latency: number;
  status: 'pending' | 'success' | 'error';
}

interface Critique {
  type: 'warning' | 'error' | 'info';
  message: string;
  source?: string;
}

interface SynthesisResult {
  decision: string;
  confidenceScore: number;
  keyPoints: string[];
  actions: string[];
  memoryNote?: string;
}

// ============================================
// Expert Card Component
// ============================================

const ExpertCard: React.FC<{ data: ExpertResponse; isLoading: boolean }> = ({
  data,
  isLoading
}) => {
  const statusColors = {
    pending: 'border-yellow-500',
    success: 'border-green-500',
    error: 'border-red-500',
  };

  return (
    <div className={`bg-gray-800 rounded-lg p-4 border-l-4 ${statusColors[data.status]}`}>
      <div className="flex justify-between items-center mb-2">
        <h3 className="font-bold text-white">{data.modelDisplay}</h3>
        {data.latency > 0 && (
          <span className="text-xs text-gray-400">{data.latency}ms</span>
        )}
      </div>

      {isLoading ? (
        <div className="animate-pulse">
          <div className="h-4 bg-gray-700 rounded w-3/4 mb-2"></div>
          <div className="h-4 bg-gray-700 rounded w-1/2"></div>
        </div>
      ) : (
        <>
          <p className="text-gray-300 text-sm mb-3 whitespace-pre-wrap">
            {data.response || 'Awaiting response...'}
          </p>
          {data.confidence > 0 && (
            <div className="flex items-center gap-2">
              <div className="flex-1 bg-gray-700 rounded-full h-2">
                <div
                  className="bg-blue-500 h-2 rounded-full transition-all"
                  style={{ width: `${data.confidence}%` }}
                ></div>
              </div>
              <span className="text-xs text-gray-400">{data.confidence}%</span>
            </div>
          )}
        </>
      )}
    </div>
  );
};

// ============================================
// Katana Panel (Devil's Advocate)
// ============================================

const KatanaPanel: React.FC<{ critiques: Critique[]; isCollapsed: boolean; onToggle: () => void }> = ({
  critiques,
  isCollapsed,
  onToggle
}) => {
  if (critiques.length === 0) return null;

  const iconMap = {
    warning: '⚠️',
    error: '🚨',
    info: 'ℹ️',
  };

  return (
    <div className="bg-red-900/30 border border-red-700 rounded-lg overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full p-3 flex items-center justify-between text-left hover:bg-red-900/20"
      >
        <div className="flex items-center gap-2">
          <span className="text-xl">⚔️</span>
          <h3 className="font-bold text-red-400">Katana Mode (Devil's Advocate)</h3>
          <span className="bg-red-700 text-white text-xs px-2 py-0.5 rounded-full">
            {critiques.length}
          </span>
        </div>
        <span className="text-gray-400">{isCollapsed ? '▼' : '▲'}</span>
      </button>

      {!isCollapsed && (
        <div className="p-4 pt-0 space-y-2">
          {critiques.map((critique, index) => (
            <div key={index} className="flex items-start gap-2 text-sm">
              <span>{iconMap[critique.type]}</span>
              <span className="text-gray-300">{critique.message}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

// ============================================
// Synthesis Panel
// ============================================

const SynthesisPanel: React.FC<{ result: SynthesisResult | null; isLoading: boolean }> = ({
  result,
  isLoading
}) => {
  if (!result && !isLoading) return null;

  return (
    <div className="bg-green-900/30 border border-green-700 rounded-lg p-4">
      <div className="flex items-center justify-between mb-4">
        <h3 className="font-bold text-green-400 flex items-center gap-2">
          <span>✅</span> Final Synthesis
        </h3>
        {result && (
          <div className="flex items-center gap-2">
            <span className="text-sm text-gray-400">Confidence:</span>
            <span className={`font-bold ${
              result.confidenceScore >= 80 ? 'text-green-400' :
              result.confidenceScore >= 60 ? 'text-yellow-400' : 'text-red-400'
            }`}>
              {result.confidenceScore}%
            </span>
          </div>
        )}
      </div>

      {isLoading ? (
        <div className="animate-pulse space-y-3">
          <div className="h-6 bg-gray-700 rounded w-3/4"></div>
          <div className="h-4 bg-gray-700 rounded w-1/2"></div>
        </div>
      ) : result && (
        <div className="space-y-4">
          <div>
            <h4 className="text-sm font-semibold text-gray-400 mb-1">Decision</h4>
            <p className="text-white text-lg">{result.decision}</p>
          </div>

          {result.keyPoints.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold text-gray-400 mb-1">Key Points</h4>
              <ul className="list-disc list-inside text-gray-300 text-sm space-y-1">
                {result.keyPoints.map((point, i) => (
                  <li key={i}>{point}</li>
                ))}
              </ul>
            </div>
          )}

          {result.actions.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold text-gray-400 mb-1">Recommended Actions</h4>
              <ul className="list-decimal list-inside text-gray-300 text-sm space-y-1">
                {result.actions.map((action, i) => (
                  <li key={i}>{action}</li>
                ))}
              </ul>
            </div>
          )}

          {result.memoryNote && (
            <div className="bg-blue-900/30 border border-blue-700 rounded p-3 mt-4">
              <span className="text-blue-400 text-sm">📚 Memory: </span>
              <span className="text-gray-300 text-sm">{result.memoryNote}</span>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

// ============================================
// Main App Component
// ============================================

const App: React.FC = () => {
  const [query, setQuery] = useState<string>('');
  const [responses, setResponses] = useState<ExpertResponse[]>([
    { model: 'openai/gpt-4o', modelDisplay: 'GPT-4', response: '', confidence: 0, latency: 0, status: 'pending' },
    { model: 'anthropic/claude-3-5-sonnet', modelDisplay: 'Claude', response: '', confidence: 0, latency: 0, status: 'pending' },
    { model: 'google/gemini-pro', modelDisplay: 'Gemini', response: '', confidence: 0, latency: 0, status: 'pending' },
    { model: 'deepseek/deepseek-chat', modelDisplay: 'DeepSeek', response: '', confidence: 0, latency: 0, status: 'pending' },
  ]);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [critiques, setCritiques] = useState<Critique[]>([]);
  const [synthesis, setSynthesis] = useState<SynthesisResult | null>(null);
  const [katanaCollapsed, setKatanaCollapsed] = useState<boolean>(false);

  const handleSubmit = async () => {
    if (!query.trim()) return;

    setIsLoading(true);
    setCritiques([]);
    setSynthesis(null);

    // Simulate API call - will be replaced with actual OpenRouter integration
    setTimeout(() => {
      setResponses([
        {
          model: 'openai/gpt-4o',
          modelDisplay: 'GPT-4',
          response: 'Based on market analysis, expansion shows promise with 23% projected ROI. Key factors include market size and competitive landscape.',
          confidence: 87,
          latency: 1234,
          status: 'success'
        },
        {
          model: 'anthropic/claude-3-5-sonnet',
          modelDisplay: 'Claude',
          response: 'I recommend caution. Regulatory requirements in the target market need thorough assessment. Consider phased entry approach.',
          confidence: 82,
          latency: 1567,
          status: 'success'
        },
        {
          model: 'google/gemini-pro',
          modelDisplay: 'Gemini',
          response: 'Competitive analysis suggests moderate opportunity. Market timing appears favorable given current economic indicators.',
          confidence: 79,
          latency: 987,
          status: 'success'
        },
        {
          model: 'deepseek/deepseek-chat',
          modelDisplay: 'DeepSeek',
          response: 'Financial modeling indicates positive NPV under base case assumptions. Sensitivity analysis shows risk at currency fluctuations.',
          confidence: 84,
          latency: 756,
          status: 'success'
        },
      ]);

      setCritiques([
        { type: 'warning', message: 'Currency risk not adequately addressed by any expert' },
        { type: 'warning', message: 'GPT-4 confidence (87%) may be high given limited market data' },
        { type: 'info', message: 'Consider regulatory timeline for full compliance' },
      ]);

      setSynthesis({
        decision: 'Proceed with caution — phased market entry recommended',
        confidenceScore: 78,
        keyPoints: [
          'Market opportunity validated by all 4 experts',
          'Regulatory pathway needs clarification (Claude)',
          'Currency hedging strategy required (Katana flag)',
        ],
        actions: [
          'Commission legal due diligence ($15K budget)',
          'Develop currency hedging strategy',
          'Plan pilot market test for Q2 2026',
        ],
        memoryNote: 'Similar expansion considered in 2023 — review previous decision factors',
      });

      setIsLoading(false);
    }, 2000);
  };

  return (
    <div className="min-h-screen bg-gray-900 text-white">
      {/* Header */}
      <header className="bg-gray-800 border-b border-gray-700 p-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <h1 className="text-xl font-bold flex items-center gap-2">
            <span>🏛️</span> League of Experts
          </h1>
          <span className="text-sm text-gray-400">by Carlos Mundim © 2022-2025</span>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-6xl mx-auto p-6 space-y-6">
        {/* Query Input */}
        <div className="bg-gray-800 rounded-lg p-4">
          <textarea
            className="w-full bg-gray-700 text-white rounded-lg p-4 resize-none focus:ring-2 focus:ring-blue-500 focus:outline-none"
            rows={3}
            placeholder="Ask the League of Experts... (e.g., 'Should we expand to the US market?')"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && e.ctrlKey) handleSubmit();
            }}
          />
          <div className="flex justify-between items-center mt-3">
            <span className="text-xs text-gray-500">Press Ctrl+Enter to submit</span>
            <button
              onClick={handleSubmit}
              disabled={isLoading || !query.trim()}
              className="bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 disabled:cursor-not-allowed px-6 py-2 rounded-lg font-medium transition-colors"
            >
              {isLoading ? 'Consulting Experts...' : 'Ask the Council'}
            </button>
          </div>
        </div>

        {/* Expert Responses Grid */}
        <div>
          <h2 className="text-lg font-semibold text-gray-400 mb-3">Expert Responses</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {responses.map((response, index) => (
              <ExpertCard key={index} data={response} isLoading={isLoading} />
            ))}
          </div>
        </div>

        {/* Katana Mode */}
        <KatanaPanel
          critiques={critiques}
          isCollapsed={katanaCollapsed}
          onToggle={() => setKatanaCollapsed(!katanaCollapsed)}
        />

        {/* Synthesis */}
        <SynthesisPanel result={synthesis} isLoading={isLoading} />

        {/* Footer Actions */}
        {synthesis && (
          <div className="flex justify-center gap-4">
            <button className="bg-gray-700 hover:bg-gray-600 px-4 py-2 rounded-lg text-sm">
              💾 Save to Memory
            </button>
            <button className="bg-gray-700 hover:bg-gray-600 px-4 py-2 rounded-lg text-sm">
              📤 Export Report
            </button>
            <button className="bg-gray-700 hover:bg-gray-600 px-4 py-2 rounded-lg text-sm">
              🔄 Re-query
            </button>
          </div>
        )}
      </main>
    </div>
  );
};

export default App;
