// main.ts - League of Experts Electron Entry Point
// Generated by Codex, reviewed by Tiger

import { app, BrowserWindow, ipcMain } from 'electron';
import path from 'path';

// Define types
interface Settings {
  theme: 'dark' | 'light';
  apiKey: string;
  chairmanModel: string;
  expertModels: string[];
}

interface ExpertQuery {
  query: string;
  models: string[];
}

let mainWindow: BrowserWindow | null = null;

function createWindow(): void {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    minWidth: 900,
    minHeight: 600,
    title: 'League of Experts',
    backgroundColor: '#1f2937', // Dark gray
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js'),
    },
  });

  // Load based on environment
  const isDev = process.env.NODE_ENV === 'development';
  const startUrl = isDev
    ? 'http://localhost:5173'
    : `file://${path.join(__dirname, '../dist/index.html')}`;

  mainWindow.loadURL(startUrl);

  // Dev tools in development
  if (isDev) {
    mainWindow.webContents.openDevTools();
  }

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// App lifecycle
app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// IPC Handlers

// Query experts through OpenRouter
ipcMain.handle('queryExperts', async (_event, { query, models }: ExpertQuery) => {
  console.log(`[LoE] Query received: ${query}`);
  console.log(`[LoE] Models: ${models.join(', ')}`);
  // Actual implementation will call OpenRouter API
  // For now, return placeholder
  return { status: 'pending', query, models };
});

// Get stored memory/history
ipcMain.handle('getMemory', async () => {
  console.log('[LoE] Memory request');
  // Will integrate with Tiger Mind V2
  return { conversations: [], lastQuery: null };
});

// Save settings
ipcMain.handle('saveSettings', async (_event, settings: Settings) => {
  console.log('[LoE] Saving settings');
  // Will save to secure storage
  return { success: true };
});

// Get settings
ipcMain.handle('getSettings', async () => {
  // Will load from secure storage
  return {
    theme: 'dark',
    apiKey: '',
    chairmanModel: 'anthropic/claude-3-opus',
    expertModels: [
      'openai/gpt-4o',
      'anthropic/claude-3-5-sonnet',
      'google/gemini-pro',
      'deepseek/deepseek-chat',
    ],
  };
});

console.log('[League of Experts] Electron main process started');
